### ISSUE TITLE
Extension breaks Google Photos UI

### ISSUE THREAD

**Issue by ZaLiTHkA** [Ademking/BetterViewer#10]
I've discovered a rather finicky issue here with Google Photos, seems to be reliably reproducible as well..

1. launch Google Photos
2. open any picture
3. select "Download" from the "More options" menu (kebab icon, top right)
4. select the "Back" arrow from the top left

at this point, you should be left with your Google Photos thumbnail gallery view, and BetterViewer's UI controls overlay. the only way to clear this state is by reloading the page.

this "Download" step is critical to reproducing this issue though; even if you open the "More options" menu and then back out of the image, BetterViewer UI does not come up unless you explicitly download the image.

I do have other extensions installed, though none relating to image viewing, so I _doubt_ they would be causing any conflicts here.. so if you are unable to reproduce the issue, please do let me know so I can do some more thorough testing.

---

my current environment:

* OS: Windows 10 Pro x64 21H2 build 19044.1466
* Browser: Chrome 97.0.4692.71

**Comment by Ademking** [comment]
Hello @ZaLiTHkA,
Sorry for the late reply! Everything is working now. Please check version 1.0.3
Thank you so much!

**Comment by ZaLiTHkA** [comment]
no worries, thanks for the update.. the `1.0.3` changelog includes some nice fixes. 👍🏼 

I installed this through the Chrome Web Store, which still lists `1.0.2` as the latest. I'm guessing it will take a little time for the update to filter through there as well?

**Comment by Ademking** [comment]
@ZaLiTHkA Thank you ^_^
Yes you're right.. It's pending review. Maybe after 1 or 2 days It will be updated.
