### ISSUE TITLE
Image being Blocked by other extension since recent Update

### ISSUE THREAD

**Issue by charakaSamawry** [Ademking/BetterViewer#13]
As of recently another extension (https://github.com/RomanistHere/PopUpOFF) which blocks annoying cookie banners/popups on sites so you dont have to click disable/accept, is blocking the picture from loading with your extension. 
Ive always used both extensions successfully but as of a recent update PopUpOff has started blocking the image unless set to dormant (off) which isnt the setting i want for the site where im viewing the image.

Thanks, Sam

**Comment by Ademking** [comment]
Hi @charakaSamawry,
Thank you so much for your report. I can't reproduce the issue.
See this:

https://user-images.githubusercontent.com/12462188/153785758-2d9d22ca-7412-453f-841e-16a4f15bf767.mp4

**Comment by Ademking** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest stable version.

Thank you!
