### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Ademking/BetterViewer#19]
Hi

Just discovered this great extension and see a couple things missing that would make it perfect.

1. A hover zoom feature. It's already an image extension, it would be a natural fit, and make it a fully well-rounded extension to add the usual "hover zoom", so that we don't have to also install yet another extension (hover zoom+, which has a history of malware) just for a hover zoom feature.
2. Ability to use Imgur instead of only imgbb (bonus if we can also use our own self hosted solution (ie something like Cheveretto on Docker)
3. Stamps. Some basic ones like you'd see in a default snagit installation. like numbers, emoti's, and I don't know if it's possible, but add our own, for something like a quick watermark.
4. Zoom ability when using the "paint" window.
5. Some tools in the paint window should automatically also use a select ability. ie when I go to use the pixilize tool, I repeatedly kept accidentally painting on the image and having to undo, because I'm so used to so many other tools that automatically allow you to select and pixilize in the same click and drag movement.

Just noting that these aren't complaints per-se, I love it so far; just think these additions would make it perfect, and like it should be included as a default built right into the browser itself! :)

**Comment by Ademking** [comment]
Hello @YouveGotMeowxy 👋

Thanks so much for your feedback! I'm really glad you enjoyed BetterViewer.
I'd just like to thank you for taking the time to write this feature requests. ❤️ 

I will try my best to make these features!

**Comment by Ademking** [comment]
> Hi
> 
> Just discovered this great extension and see a couple things missing that would make it perfect.
> 
> 1. A hover zoom feature. It's already an image extension, it would be a natural fit, and make it a fully well-rounded extension to add the usual "hover zoom", so that we don't have to also install yet another extension (hover zoom+, which has a history of malware) just for a hover zoom feature.
> 2. Ability to use Imgur instead of only imgbb (bonus if we can also use our own self hosted solution (ie something like Cheveretto on Docker)
> 3. Stamps. Some basic ones like you'd see in a default snagit installation. like numbers, emoti's, and I don't know if it's possible, but add our own, for something like a quick watermark.
> 4. Zoom ability when using the "paint" window.
> 5. Some tools in the paint window should automatically also use a select ability. ie when I go to use the pixilize tool, I repeatedly kept accidentally painting on the image and having to undo, because I'm so used to so many other tools that automatically allow you to select and pixilize in the same click and drag movement.
> 
> Just noting that these aren't complaints per-se, I love it so far; just think these additions would make it perfect, and like it should be included as a default built right into the browser itself! :)

------------

@YouveGotMeowxy Hello again :)

I've added some new features in 1.0.4
You can (Adjust, Draw, Watermark, Filters, Finetune, Resize, Export As PNG, JPEG, JPG, WEBP)

In short, I've added your suggestions (3, 4 and 5)

Waiting for your reply. Thank you








![image](https://user-images.githubusercontent.com/12462188/163969325-e321c4a7-4fc1-4a64-836d-2ee2e0ef5bd2.png)

**Comment by YouveGotMeowxy** [comment]
@Ademking Thank you!
