### ISSUE TITLE
Original image showed in background together with main picture.

### ISSUE THREAD

**Issue by ZSasha0** [Ademking/BetterViewer#21]
When I do "open image in a new tab", the image is indeed opened in a new tab, however I can still see the same image displayed at the bottom half of the screen, as a background. Trying to change theme (light, dark, blurried) - did not help.
Please see this screenshots:
[https://imgur.com/MnYhNHZ](https://imgur.com/MnYhNHZ)
[https://imgur.com/h5pH4mW](https://imgur.com/h5pH4mW)

My system: Windows 11 Pro 
Version 10.0.22000 Build 22000

Screen resolution: 2560 x 1440 x 74Hz
Bits/Pixel: 32

Browser:
Microsoft Edge
Version 100.0.1185.36 (Official build) (64-bit)

**Comment by Ademking** [comment]
Thank you @ZSasha0 for your feedback! 
Can you disable all extensions except "BetterViewer (latest version)" and test again ?

**Comment by notPlancha** [comment]
It's also happening the same thing to me, even in a fresh install of the latest chrome
![image](https://user-images.githubusercontent.com/31565873/163263402-88ed2929-2bec-4d51-bf28-def38a751973.png)

**Comment by Xpert104** [comment]
Having same issue as well.

**Comment by Ademking** [comment]
Thanks to @patrykdziurkowski, he fixed this issue! #22 Keep up the good work 👍 
This update will be available very soon in Chrome, Edge and Firefox stores

![image](https://user-images.githubusercontent.com/12462188/163913730-1f2e411d-12c6-46cc-b113-69aab0c53d1e.png)
