### ISSUE TITLE
Can no longer draw in new photo editor

### ISSUE THREAD

**Issue by AymanAliS** [Ademking/BetterViewer#24]
Love the new photo editor on the latest version(1.0.5). But it seems the draw feature is no longer there.

**Comment by Ademking** [comment]
Hello @AymanAliS, 
It's there my friend. Please check again

![image](https://user-images.githubusercontent.com/12462188/165443502-81ecfd43-53eb-49cf-a515-3368f41c1930.png)

**Comment by AymanAliS** [comment]
Oh, sorry about that. But I can't choose different colors now, only black. Is that intentional?

**Comment by AymanAliS** [comment]
Sorry about that, this new layout is a little confusing for me.

**Comment by Ademking** [comment]
No problem @AymanAliS 👍  I'm closing this issue
