### ISSUE TITLE
Allow adjusting zoom speed

### ISSUE THREAD

**Issue by nNoidea** [Ademking/BetterViewer#29]
Allow us to zoom in slower or faster by changing the speed through the settings.

I feel like the current zoom in speed is too slow, but some people might also find it fast or perfect. So a customizable setting would be great!

Also, it's an amazing and clean extension <3!

**Comment by ArgonAlex** [comment]
There also might be a kind of bug here too. I noticed that when I use my scrollwheel with one slower+longer continous scroll, it zooms
noticably faster than using mutiple rapid+shorter scrolls. This feels counterintuitive.
