### ISSUE TITLE
Alt+D hijacking?

### ISSUE THREAD

**Issue by SpitFire-666** [Ademking/BetterViewer#31]
**Describe the bug**

When viewing an image in BetterViewer tab, the Alt+D key combo to focus the address bar no longer works

**To Reproduce**
1. Open an image so that BetterViewer loads it
3. Press Alt+D (on Windows at least)

**Expected behavior**
Address bar should be focused, but isn't - I think BetterViewer is hijacking that keyboard shortcut

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: firefox
 - Version: 100 (tried on 2 PCs)

**Additional context**
This may be by design and not a bug 🤷‍♂️, but I use Alt+D (standard shortcut for focusing the address bar since the dawn of time) all the time! Thanks

**Comment by Ademking** [comment]
@SpitFire-666 Thank you so much for your feedback! 👍 You're right. 
I will fix this and It will be in the available in the next update

**Comment by SpitFire-666** [comment]
Also just noticed F5 and Ctrl+R don't work (I want to refresh the image for testing). Can raise another issue if you want. Cheers!

**Comment by skagon** [comment]
I will second that and also add that even Ctrl+S has been rendered inoperative. I can't save the image at all, which is highly annoying. Please fix that also.

**Comment by W0ofles** [comment]
Can we possibly make the Ctrl+D a toggle-able option? I saw the notification for the bug and went to test it and I actually kind of like that it displays details and doesn't highlight the address bar

**Comment by Sevenics** [comment]
I also find it terribly irritating how Ctrl+P, and generally universal shotcut to Print, is no longer Print.
Instead It opens Paint, a function I have no interest in. And disabling the paint function simply make Ctrl+P a dead shortcut.

Instead Print has been rebound to Ctrl+M, a shortcut that makes it conflict with Firefox Mute Tab shortkey.
