### ISSUE TITLE
[Request] Maximise image button

### ISSUE THREAD

**Issue by ewanhowell5195** [Ademking/BetterViewer#33]
A maximise button would scale the image to display as large as it can.
This is different from fullscreen as fullscreen takes up the whole screen, whereas this makes the image large enough to fill the window.

An auto-maximise option would also be nice, where when opening an image it will automatically be maximised, and then from there you can resize it however you like.

This would be useful for viewing things like pixel art, which by default will display really small, and can be annoying to constantly zoom in to see.

**Comment by Ademking** [comment]
Hello @ewanhowell5195,
I think you're talking about 1:1 ratio
See this:
![image](https://user-images.githubusercontent.com/12462188/168696789-5384e644-8b89-4659-8a4a-372640639e7b.png)


Try using it with this example:

https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg

**Comment by ewanhowell5195** [comment]
I am not talking about 1:1 ratio.

I am talking about making images scale to fill the window, aka "maximising"

See this image: https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.18.2/assets/minecraft/textures/block/dirt.png

It shows really small as the image is really small, and 1:1 doesn't change that.

Maximise would change it to display scaled up like this:
![image](https://user-images.githubusercontent.com/48070995/168697689-779cbb6a-f639-4b3c-832a-cf75dd793dc2.png)
