### ISSUE TITLE
[Request] The ability to change the zoom speed

### ISSUE THREAD

**Issue by ewanhowell5195** [Ademking/BetterViewer#35]
Having the ability to adjust the speed at which you can zoom in and out with the scroll wheel would be great, as the default speed is really slow and gets annoying having to constantly zoom into small images really slowly.

**Comment by Ademking** [comment]
Thank you @ewanhowell5195 for your feedback 👍 
Duplicate of #29

**Comment by ewanhowell5195** [comment]
Love the extension btw, just a few small tweaks and then it would be perfect for me
