### ISSUE TITLE
Open locally saved image files

### ISSUE THREAD

**Issue by PolyTimotheos** [Ademking/BetterViewer#37]
I really would like to see support for images saved on my hard drive, because this image viewer is actually a lot better than most dedicated image viewer apps out there.

I tried enabling "Allow access to file URLs" but that didn't help.

This would only be really useful if it opened local images directly in the viewer without having to open it first and then right click and open image in new tab first. i'd also like a dedicated context menu entry for instead of open image in new tab. 

Shortcuts would also be nice, especially for fullscreen.

Anyways, i really appreciate the work you've done here! The result is surely magnificient and from my view it's only those few things that are holding me back from deleting every image viewer app on my pc and only using Better Viewer.

**Comment by ZaLiTHkA** [comment]
in the meantime, you can view local files in your browser using BetterView by running a local web server..

execute `npx serve .` from any folder that contains images and open the provided URL. (:
