### ISSUE TITLE
Any Plans for Firefox

### ISSUE THREAD

**Issue by Lalit64** [Ademking/BetterViewer#4]

**Comment by Ademking** [comment]
@Lalit64 I'm working on it right now! It will be available soon 👍

**Comment by Lalit64** [comment]
Thanks

**Comment by Ademking** [comment]
@Lalit64 BetterViewer is now supporting Firefox 🦊 👍  Sorry for being late

**Comment by Ademking** [comment]
Thank you @Kamoba 👍

**Comment by Lalit64** [comment]
Thanks sorry for the late reply 👍
