### ISSUE TITLE
Any plan to support mobile browser(like kiwi browser)

### ISSUE THREAD

**Issue by 0warning0error** [Ademking/BetterViewer#5]
I tried to install it on kiwi browser in Mi Pad 5 pro but it seemed not to work. Is there a plan to further support mobile browser like kiwi browser?

**Comment by Ademking** [comment]
@0warning0error Sorry for the late reply!
I'm sorry but I don't think that Betterviewer is working on mobile.
I don't think I can fix it 😞 Sorry about that 
If you have any idea how to make it run on mobile please tell me
Thank you

**Comment by Ademking** [comment]
@0warning0error I've tried Kiwi Browser (latest version) 98.0.4758.89 and It's working 😄 

![273228021_774600436834575_8559194132096210272_n](https://user-images.githubusercontent.com/12462188/153661458-a9408009-dbb7-42ee-820d-94e2dd47e73f.png)
![273526029_518342846246961_7879464490234707454_n](https://user-images.githubusercontent.com/12462188/153662246-638a208a-42c1-4b09-8c95-ec2d0d4d4513.png)
