### ISSUE TITLE
'Toggle theme' is not persisted

### ISSUE THREAD

**Issue by technodrome** [Ademking/BetterViewer#9]
Tested on:
- Vivaldi 5.0.2497.38 (Stable channel) stable (64-bit)
- Brave 1.33.106 Chromium: 96.0.4664.110 (Official Build) unknown (64-bit)

Actual vs. desired behavior:
- When clicking 'Toggle theme' I expect this setting to be persisted. It is not. Instead, upon each and every image, theme is reverted back to 'blurry background' one. This is disturbing at night. If the change is not persistable, this should be clearly communicated. As of now, this is not the case. In order to offer better user experience, this setting should be clearly persisted. It makes no sense to do this on per-image basis as it is not only annoying but also makes no practical contribution on per-image basis to the overall UX.

Thank you for looking into this and for your work on the extension.

**Comment by Ademking** [comment]
Hello @technodrome,
Sorry for the late reply! 
I've added persistent theme. 
![image](https://user-images.githubusercontent.com/12462188/153191203-fdec14f1-633d-4881-9f28-ce0ae07795d9.png)

Thank you so much for your suggestion 👍
